apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: logstorages.operator.tigera.io
spec:
  group: operator.tigera.io
  names:
    kind: LogStorage
    listKind: LogStorageList
    plural: logstorages
    singular: logstorage
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Specification of the desired state for Tigera log storage.
          properties:
            indices:
              description: Index defines the configuration for the indices in the
                Elasticsearch cluster.
              properties:
                replicas:
                  description: Replicas defines how many replicas each index will
                    have. See https://www.elastic.co/guide/en/elasticsearch/reference/current/scalability.html
                  format: int64
                  type: integer
              required:
              - replicas
              type: object
            nodes:
              description: Nodes defines the configuration for a set of identical
                Elasticsearch cluster nodes, each of type master, data, and ingest.
              properties:
                count:
                  description: Count defines the number of nodes in the Elasticsearch
                    cluster.
                  format: int64
                  type: integer
                resourceRequirements:
                  description: ResourceRequirements defines the resource limits and
                    requirements for the Elasticsearch cluster.
                  type: object
              type: object
            retention:
              description: Retention defines how long data is retained in the Elasticsearch
                cluster before it is cleared.
              properties:
                auditReports:
                  description: 'AuditReports configures the retention period for audit
                    logs, in days.  Logs written on a day that started at least this
                    long ago are removed.  To keep logs for at least x days, use a
                    retention period of x+1. Default: 91'
                  format: int32
                  type: integer
                complianceReports:
                  description: 'ComplianceReports configures the retention period
                    for compliance reports, in days. Reports are output from the analysis
                    of the system state and audit events for compliance reporting.
                    Consult the Compliance Reporting documentation for more details
                    on reports. Logs written on a day that started at least this long
                    ago are removed.  To keep logs for at least x days, use a retention
                    period of x+1. Default: 91'
                  format: int32
                  type: integer
                flows:
                  description: 'Flows configures the retention period for flow logs,
                    in days.  Logs written on a day that started at least this long
                    ago are removed.  To keep logs for at least x days, use a retention
                    period of x+1. Default: 8'
                  format: int32
                  type: integer
                snapshots:
                  description: 'Snapshots configures the retention period for snapshots,
                    in days. Snapshots are periodic captures of resources which along
                    with audit events are used to generate reports. Consult the Compliance
                    Reporting documentation for more details on snapshots. Logs written
                    on a day that started at least this long ago are removed.  To
                    keep logs for at least x days, use a retention period of x+1.
                    Default: 91'
                  format: int32
                  type: integer
                maxTotalStoragePercent:
                  description: 'TSEE uses a default high watermark threshold (90%) for
                    rotating indices in the Elasticsearch cluster. Indices are deleted
                    (starting with the oldest) when the disk exceeds this threshold.
                    Lowering the value leads to lower disk utilization, while increasing
                    it by too much can have an impact on the stability of your cluster.
                    Default: 90'
                  format: int32
                  type: integer
                maxLogsStoragePercent:
                  description: 'TSEE will remove dns and flow log indices once the combined data
                    exceeds this threshold. The default value (80% of the cluster size) is used
                    because flow logs and dns logs often use the most disk space; this allows
                    compliance and security indices to be retained longer. The oldest indices are
                    removed first. Set this value to be lower than or equal to, the value for
                    max-total-storage-pct.
                    Default: 80'
                  format: int32
                  type: integer
              required:
              - flows
              - auditReports
              - snapshots
              - complianceReports
              type: object
          type: object
        status:
          description: Most recently observed state for Tigera log storage.
          properties:
            elasticsearchHash:
              description: ElasticsearchHash represents the current revision and configuration
                of the installed Elasticsearch cluster. This is an opaque string which
                can be monitored for changes to perform actions when Elasticsearch
                is modified.
              type: string
            kibanaHash:
              description: KibanaHash represents the current revision and configuration
                of the installed Kibana dashboard. This is an opaque string which
                can be monitored for changes to perform actions when Kibana is modified.
              type: string
            state:
              description: State provides user-readable status.
              type: string
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
